### ISSUE TITLE
How to make it work with proxies

### ISSUE THREAD

**Issue by jokinvipo** [jf-m/earning-machine#1]
Hey,
Thank you for your project.

How can i make it work using proxies?

**Comment by jf-m** [comment]
Hi @jokinvipo ,

You'll need to configure the proxy on the Docker engine level.

You can follow the steps here: https://docs.docker.com/network/proxy/

Basically, it's just creating a `~/.docker/config.json` file with the following content 

```
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://192.168.1.12:3128",
     "httpsProxy": "http://192.168.1.12:3128",
     "noProxy": "*.test.example.com,.example2.com,127.0.0.0/8"
   }
 }
}
```

**Comment by jokinvipo** [comment]
Hey,

I have tested but dont work because i have https with credentials proxys

**Comment by jf-m** [comment]
Have you tried using `https://<my_usename>:<my_password>@my_proxy.com:proxy_port` ?

If your password includes special characters, maybe [urlencode](https://www.urlencoder.io/) it ?

If it's not working, you should probably search [here](https://github.com/docker/cli/issues?q=proxy) and open an issue there if you don't find your answer.
